#!/usr/bin/env bash

pm uninstall --user 0 'com.coloros.activation'
pm uninstall --user 0 'com.coloros.childrenspace'
pm uninstall --user 0 'com.coloros.compass2'
pm uninstall --user 0 'com.coloros.filemanager'
pm uninstall --user 0 'com.coloros.floatassistant'
pm uninstall --user 0 'com.coloros.gallery3d'
pm uninstall --user 0 'com.coloros.healthcheck'
pm uninstall --user 0 'com.coloros.karaoke'
pm uninstall --user 0 'com.coloros.ocs.opencapabil'
pm uninstall --user 0 'com.coloros.operationManual'
pm uninstall --user 0 'com.coloros.oshare'
pm uninstall --user 0 'com.coloros.phonemanager'
pm uninstall --user 0 'com.coloros.scenemode'
pm uninstall --user 0 'com.coloros.securepay'
pm uninstall --user 0 'com.coloros.smartsidebar'
pm uninstall --user 0 'com.coloros.soundrecorder'
pm uninstall --user 0 'com.coloros.video'
pm uninstall --user 0 'com.coloros.weather.service'
pm uninstall --user 0 'com.coloros.weather2'
pm uninstall --user 0 'com.debug.loggerui'
pm uninstall --user 0 'com.fintech.life'
pm uninstall --user 0 'com.glance.internet'
pm uninstall --user 0 'com.heytap.accessory'
pm uninstall --user 0 'com.heytap.browser'
pm uninstall --user 0 'com.heytap.market'
pm uninstall --user 0 'com.heytap.mcs'
pm uninstall --user 0 'com.heytap.music'
pm uninstall --user 0 'com.heytap.pictorial'
pm uninstall --user 0 'com.heytap.usercenter'
pm uninstall --user 0 'com.payjoy.access'
pm uninstall --user 0 'com.wapi.wapicertmanager'

# OnePlus Ltd.

pm uninstall --user 0 'com.oplus.account'
pm uninstall --user 0 'com.oplus.aiunit'
pm uninstall --user 0 'com.oplus.aod'
pm uninstall --user 0 'com.oplus.apprecover'
pm uninstall --user 0 'com.oplus.atlas'
pm uninstall --user 0 'com.oplus.bttestmode'
pm uninstall --user 0 'com.oplus.cast'
pm uninstall --user 0 'com.oplus.commercial'
pm uninstall --user 0 'com.oplus.cosa'
pm uninstall --user 0 'com.oplus.cota'
pm uninstall --user 0 'com.oplus.crashbox'
pm uninstall --user 0 'com.oplus.customize.coreapp'
pm uninstall --user 0 'com.oplus.encryption'
pm uninstall --user 0 'com.oplus.engineercamera'
pm uninstall --user 0 'com.oplus.engineermode'
pm uninstall --user 0 'com.oplus.engineernetwork'
pm uninstall --user 0 'com.oplus.games'
pm uninstall --user 0 'com.oplus.healthservice'
pm uninstall --user 0 'com.oplus.interconnectcollectkit'
pm uninstall --user 0 'com.oplus.lfeh'
pm uninstall --user 0 'com.oplus.linker'
pm uninstall --user 0 'com.oplus.logkit'
pm uninstall --user 0 'com.oplus.melody'
pm uninstall --user 0 'com.oplus.multiapp'
pm uninstall --user 0 'com.oplus.nas'
pm uninstall --user 0 'com.oplus.ocloud'
pm uninstall --user 0 'com.oplus.olc'
pm uninstall --user 0 'com.oplus.onet'
pm uninstall --user 0 'com.oplus.onetrace'
pm uninstall --user 0 'com.oplus.payjoy'
pm uninstall --user 0 'com.oplus.postmanservice'
pm uninstall --user 0 'com.oplus.qualityprotect'
pm uninstall --user 0 'com.oplus.screenrecorder'
pm uninstall --user 0 'com.oplus.smartengine'
pm uninstall --user 0 'com.oplus.statistics.rom'
pm uninstall --user 0 'com.oplus.synergy'
pm uninstall --user 0 'com.oplus.themestore'
pm uninstall --user 0 'com.oplus.viewtalk'
pm uninstall --user 0 'com.oplus.wifibackuprestore'
pm uninstall --user 0 'com.ses.entitlement.o2'

# Oppo

pm uninstall --user 0 'com.oppo.quicksearchbox'

# Realme

pm uninstall --user 0 'com.realme.movieshot'
pm uninstall --user 0 'com.realme.wellbeing'

# Realtek

pm uninstall --user 0 'com.Btek.engineermode'
pm uninstall --user 0 'com.Btek.omacp'
pm uninstall --user 0 'com.Btek.voicecommand'

# Tencent Inc.

pm uninstall --user 0 'com.tencent.soter.soterserver'
